-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    city_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(100) NOT NULL,
    PRIMARY KEY (city_id)
);

CREATE TABLE public.cv_educations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    university_id integer NOT NULL,
    school_type character varying(50) NOT NULL,
    edu_beginning_date date NOT NULL,
    graduation_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_languages
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    foreign_language_id integer NOT NULL,
    language_level_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_skills
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    programming_language character varying NOT NULL,
    cv_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cvs
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    github_link character varying(255) NOT NULL,
    linkedin_link character varying(255) NOT NULL,
    cover_letter character varying(500) NOT NULL,
    creation_date timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    web_address character varying(100) NOT NULL,
    phone_number character varying(16) NOT NULL,
    verification_status boolean NOT NULL,
    update_employer json,
    update_status boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.faculties
(
    id integer NOT NULL,
    faculty_name character varying NOT NULL,
    university_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.favorites
(
    favorite_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9000000 CACHE 1 ),
    job_advertisement_id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    PRIMARY KEY (favorite_id)
);

CREATE TABLE public.foreign_languages
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisements
(
    job_advertisement_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 23504 CACHE 1 ),
    city_id integer NOT NULL,
    job_description character varying(100) NOT NULL,
    max_salary integer,
    min_salary integer,
    position_amount integer NOT NULL,
    application_deadline date NOT NULL,
    advertisement_status boolean NOT NULL,
    employer_id integer NOT NULL,
    position_id integer NOT NULL,
    release_date date NOT NULL,
    approval_status boolean NOT NULL,
    work_time_type_id integer NOT NULL,
    work_type_id integer NOT NULL,
    PRIMARY KEY (job_advertisement_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    identity_number character varying(11) NOT NULL,
    date_of_birth integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.language_levels
(
    language_level_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    language_level integer NOT NULL,
    PRIMARY KEY (language_level_id)
);

CREATE TABLE public.photos
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    photo_url character varying(500) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.sections
(
    id integer NOT NULL,
    university_id integer NOT NULL,
    section_name character varying NOT NULL,
    faculty_id integer NOT NULL,
    status integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_users
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.universities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    university_name character varying,
    city_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_experiences
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    position_id integer NOT NULL,
    workplace_name character varying(100) NOT NULL,
    starting_date date NOT NULL,
    ending_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_time_types
(
    work_time_type_id integer NOT NULL,
    work_time_type_name character varying(100) NOT NULL,
    PRIMARY KEY (work_time_type_id)
);

CREATE TABLE public.work_types
(
    work_type_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 900000 CACHE 1 ),
    work_type_name character varying(100) NOT NULL,
    PRIMARY KEY (work_type_id)
);

ALTER TABLE public.cv_educations
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_educations
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (foreign_language_id)
    REFERENCES public.foreign_languages (id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (language_level_id)
    REFERENCES public.language_levels (language_level_id)
    NOT VALID;


ALTER TABLE public.cv_skills
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cvs
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.faculties
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (id)
    NOT VALID;


ALTER TABLE public.favorites
    ADD FOREIGN KEY (job_advertisement_id)
    REFERENCES public.job_advertisements (job_advertisement_id)
    NOT VALID;


ALTER TABLE public.favorites
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (work_time_type_id)
    REFERENCES public.work_time_types (work_time_type_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (work_type_id)
    REFERENCES public.work_types (work_type_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.sections
    ADD FOREIGN KEY (faculty_id)
    REFERENCES public.faculties (id)
    NOT VALID;


ALTER TABLE public.system_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.universities
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id)
    NOT VALID;


ALTER TABLE public.work_experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.work_experiences
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;

END;