-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_educations
(
    cv_edu_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    university_id integer NOT NULL,
    school_type character varying,
    edu_beginning_date date NOT NULL,
    graduation_date date,
    PRIMARY KEY (cv_edu_id)
);

CREATE TABLE public.cv_experiences
(
    experience_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company character varying,
    position_name character varying,
    job_beginning_date date NOT NULL,
    user_id integer NOT NULL,
    job_ending_date date,
    PRIMARY KEY (experience_id)
);

CREATE TABLE public.cv_languages
(
    cv_language_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    language_id integer NOT NULL,
    language_level integer NOT NULL,
    PRIMARY KEY (cv_language_id)
);

CREATE TABLE public.cv_prewritings
(
    cv_prewriting_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    prewriting character varying NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (cv_prewriting_id)
);

CREATE TABLE public.cv_skills
(
    skill_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    programming_language character varying NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (skill_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    website character varying(100) NOT NULL,
    phone_number character varying(10) NOT NULL,
    verification_status boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.faculties
(
    faculty_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    faculty_name character varying NOT NULL,
    university_id integer NOT NULL,
    status integer NOT NULL,
    PRIMARY KEY (faculty_id)
);

CREATE TABLE public.job_advertisement
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    job_position_id integer NOT NULL,
    city_id integer NOT NULL,
    job_description character varying(500) NOT NULL,
    min_salary integer,
    max_salary integer,
    number_of_open_positions integer NOT NULL,
    application_deadline character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    creation_date character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    identification_number character varying(11) NOT NULL,
    birth_year integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.languages
(
    language_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    language_name character varying NOT NULL,
    PRIMARY KEY (language_id)
);

CREATE TABLE public.links
(
    link_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    link_address character varying,
    created_on time without time zone,
    PRIMARY KEY (link_id)
);

CREATE TABLE public.photographs
(
    photograph_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    photograph_link character varying,
    created_on timestamp with time zone,
    PRIMARY KEY (photograph_id)
);

CREATE TABLE public.sections
(
    section_id integer NOT NULL,
    university_id integer NOT NULL,
    section_name character varying NOT NULL,
    faculty_id integer NOT NULL,
    status integer NOT NULL,
    PRIMARY KEY (section_id)
);

CREATE TABLE public.system_personnel
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.universities
(
    university_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    university_name character varying,
    city_id integer NOT NULL,
    status integer,
    PRIMARY KEY (university_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 9 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(250) NOT NULL,
    password character varying(250) NOT NULL,
    status boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification
(
    user_id integer NOT NULL,
    email_verification character varying(50) NOT NULL,
    is_verified boolean NOT NULL,
    verification_date timestamp without time zone NOT NULL,
    PRIMARY KEY (user_id)
);

ALTER TABLE public.cv_educations
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (university_id)
    NOT VALID;


ALTER TABLE public.cv_educations
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.cv_experiences
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (language_id)
    REFERENCES public.languages (language_id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.cv_prewritings
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.cv_skills
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.faculties
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (university_id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.links
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.photographs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.sections
    ADD FOREIGN KEY (faculty_id)
    REFERENCES public.faculties (faculty_id)
    NOT VALID;


ALTER TABLE public.system_personnel
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.universities
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.verification
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;