-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employer_verifications
(
    verification_code_id integer NOT NULL,
    employer_id integer NOT NULL,
    system_user_confirm_id integer NOT NULL,
    PRIMARY KEY (verification_code_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    web_address character varying(100) NOT NULL,
    phone_number character varying(16) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seeker_verifications
(
    verification_code_id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    PRIMARY KEY (verification_code_id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    identity_number character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_users
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_users_confirms
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    system_user_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirmed_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_codes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying(8) NOT NULL,
    is_code_confirmed boolean NOT NULL,
    confirmed_date date NOT NULL,
    is_activated boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employer_verifications
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employer_verifications
    ADD FOREIGN KEY (system_user_confirm_id)
    REFERENCES public.system_users_confirms (id)
    NOT VALID;


ALTER TABLE public.employer_verifications
    ADD FOREIGN KEY (verification_code_id)
    REFERENCES public.verification_codes (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seeker_verifications
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.job_seeker_verifications
    ADD FOREIGN KEY (verification_code_id)
    REFERENCES public.verification_codes (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_users_confirms
    ADD FOREIGN KEY (system_user_id)
    REFERENCES public.system_users (user_id)
    NOT VALID;

END;
