INSERT INTO public.universities (id, university_name, city_id) VALUES (1, 'Abant İzzet Baysal Üniversitesi', 14);
INSERT INTO public.universities (id, university_name, city_id) VALUES (2, 'Abdullah Gül Üniversitesi', 38);
INSERT INTO public.universities (id, university_name, city_id) VALUES (3, 'Acıbadem Mehmet Ali Aydınlar Üniversitesi', 1);
INSERT INTO public.universities (id, university_name, city_id) VALUES (4, 'Adana Bilim Ve Teknoloji Üniversitesi', 1);
INSERT INTO public.universities (id, university_name, city_id) VALUES (5, 'Adıyaman Üniversitesi', 2);
INSERT INTO public.universities (id, university_name, city_id) VALUES (6, 'Adnan Menderes Üniversitesi', 9);
INSERT INTO public.universities (id, university_name, city_id) VALUES (7, 'Afyon Kocatepe Üniversitesi', 3);
INSERT INTO public.universities (id, university_name, city_id) VALUES (8, 'Ağrı İbrahim Çeçen Üniversitesi', 4);
INSERT INTO public.universities (id, university_name, city_id) VALUES (9, 'Ahi Evran Üniversitesi', 40);
INSERT INTO public.universities (id, university_name, city_id) VALUES (10, 'Akdeniz Üniversitesi', 7);
INSERT INTO public.universities (id, university_name, city_id) VALUES (11, 'Aksaray Üniversitesi', 68);
INSERT INTO public.universities (id, university_name, city_id) VALUES (12, 'Alanya Alaaddin Keykubat Üniversitesi', 7);
INSERT INTO public.universities (id, university_name, city_id) VALUES (13, 'Alanya Hamdullah Emin Paşa Üniversitesi', 7);
INSERT INTO public.universities (id, university_name, city_id) VALUES (14, 'Altınbaş Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (15, 'Amasya Üniversitesi', 5);
INSERT INTO public.universities (id, university_name, city_id) VALUES (16, 'Anadolu Üniversitesi', 26);
INSERT INTO public.universities (id, university_name, city_id) VALUES (17, 'Ankara Sosyal Bilimler Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (18, 'Ankara Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (19, 'Ankara Yıldırım Beyazıt Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (20, 'Antalya Akev Üniversitesi', 7);
INSERT INTO public.universities (id, university_name, city_id) VALUES (21, 'Antalya Bilim Üniversitesi', 7);
INSERT INTO public.universities (id, university_name, city_id) VALUES (22, 'Ardahan Üniversitesi', 75);
INSERT INTO public.universities (id, university_name, city_id) VALUES (23, 'Artvin Çoruh Üniversitesi', 8);
INSERT INTO public.universities (id, university_name, city_id) VALUES (24, 'Ataşehir Adıgüzel Meslek Yüksekokulu', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (25, 'Atatürk Üniversitesi', 25);
INSERT INTO public.universities (id, university_name, city_id) VALUES (26, 'Atılım Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (27, 'Avrasya Üniversitesi', 61);
INSERT INTO public.universities (id, university_name, city_id) VALUES (28, 'Avrupa Meslek Yüksekokulu', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (29, 'Bahçeşehir Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (30, 'Balıkesir Üniversitesi', 10);
INSERT INTO public.universities (id, university_name, city_id) VALUES (31, 'Bandırma Onyedi Eylül Üniversitesi', 10);
INSERT INTO public.universities (id, university_name, city_id) VALUES (32, 'Bartın Üniversitesi', 74);
INSERT INTO public.universities (id, university_name, city_id) VALUES (33, 'Başkent Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (34, 'Batman Üniversitesi', 72);
INSERT INTO public.universities (id, university_name, city_id) VALUES (35, 'Bayburt Üniversitesi', 69);
INSERT INTO public.universities (id, university_name, city_id) VALUES (36, 'Beykent Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (37, 'Beykoz Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (38, 'Bezm-İ Âlem Vakıf Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (39, 'Bilecik Şeyh Edebali Üniversitesi', 11);
INSERT INTO public.universities (id, university_name, city_id) VALUES (40, 'Bingöl Üniversitesi', 12);
INSERT INTO public.universities (id, university_name, city_id) VALUES (41, 'Biruni Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (42, 'Bitlis Eren Üniversitesi', 12);
INSERT INTO public.universities (id, university_name, city_id) VALUES (43, 'Boğaziçi Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (44, 'Bozok Üniversitesi', 66);
INSERT INTO public.universities (id, university_name, city_id) VALUES (45, 'Bursa Teknik Üniversitesi', 16);
INSERT INTO public.universities (id, university_name, city_id) VALUES (46, 'Bülent Ecevit Üniversitesi', 67);
INSERT INTO public.universities (id, university_name, city_id) VALUES (47, 'Canik Başarı Üniversitesi', 55);
INSERT INTO public.universities (id, university_name, city_id) VALUES (48, 'Cumhuriyet Üniversitesi', 58);
INSERT INTO public.universities (id, university_name, city_id) VALUES (49, 'Çağ Üniversitesi', 33);
INSERT INTO public.universities (id, university_name, city_id) VALUES (50, 'Çanakkale Onsekiz Mart Üniversitesi', 17);
INSERT INTO public.universities (id, university_name, city_id) VALUES (51, 'Çankaya Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (52, 'Çankırı Karatekin Üniversitesi', 18);
INSERT INTO public.universities (id, university_name, city_id) VALUES (53, 'Çukurova Üniversitesi', 1);
INSERT INTO public.universities (id, university_name, city_id) VALUES (54, 'Dicle Üniversitesi', 21);
INSERT INTO public.universities (id, university_name, city_id) VALUES (55, 'Doğuş Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (56, 'Dokuz Eylül Üniversitesi', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (57, 'Dumlupınar Üniversitesi', 43);
INSERT INTO public.universities (id, university_name, city_id) VALUES (58, 'Düzce Üniversitesi', 81);
INSERT INTO public.universities (id, university_name, city_id) VALUES (59, 'Ege Üniversitesi', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (60, 'Erciyes Üniversitesi', 38);
INSERT INTO public.universities (id, university_name, city_id) VALUES (61, 'Erzincan Üniversitesi', 24);
INSERT INTO public.universities (id, university_name, city_id) VALUES (62, 'Erzurum Teknik Üniversitesi', 25);
INSERT INTO public.universities (id, university_name, city_id) VALUES (63, 'Eskişehir Osmangazi Üniversitesi', 26);
INSERT INTO public.universities (id, university_name, city_id) VALUES (64, 'Faruk Saraç Tasarım Meslek Yüksekokulu', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (65, 'Fatih Sultan Mehmet Vakıf Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (66, 'Fırat Üniversitesi', 25);
INSERT INTO public.universities (id, university_name, city_id) VALUES (67, 'Galatasaray Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (68, 'Gazi Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (69, 'Gaziantep Üniversitesi', 27);
INSERT INTO public.universities (id, university_name, city_id) VALUES (70, 'Gaziosmanpaşa Üniversitesi', 60);
INSERT INTO public.universities (id, university_name, city_id) VALUES (71, 'Gebze Teknik Üniversitesi', 41);
INSERT INTO public.universities (id, university_name, city_id) VALUES (72, 'Giresun Üniversitesi', 28);
INSERT INTO public.universities (id, university_name, city_id) VALUES (73, 'Gümüşhane Üniversitesi', 29);
INSERT INTO public.universities (id, university_name, city_id) VALUES (74, 'Hacettepe Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (75, 'Hakkari Üniversitesi', 30);
INSERT INTO public.universities (id, university_name, city_id) VALUES (76, 'Haliç Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (77, 'Harran Üniversitesi', 63);
INSERT INTO public.universities (id, university_name, city_id) VALUES (78, 'Hasan Kalyoncu Üniversitesi', 27);
INSERT INTO public.universities (id, university_name, city_id) VALUES (79, 'Hitit Üniversitesi', 19);
INSERT INTO public.universities (id, university_name, city_id) VALUES (80, 'Iğdır Üniversitesi', 76);
INSERT INTO public.universities (id, university_name, city_id) VALUES (81, 'Işık Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (82, 'İbn Haldun Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (83, 'İhsan Doğramacı Bilkent Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (84, 'İnönü Üniversitesi', 44);
INSERT INTO public.universities (id, university_name, city_id) VALUES (85, 'İskenderun Teknik Üniversitesi', 31);
INSERT INTO public.universities (id, university_name, city_id) VALUES (86, 'İstanbul 29 Mayıs Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (87, 'İstanbul Arel Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (88, 'İstanbul Aydın Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (89, 'İstanbul Ayvansaray Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (90, 'İstanbul Bilgi Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (91, 'İstanbul Bilim Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (92, 'İstanbul Esenyurt Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (93, 'İstanbul Gedik Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (94, 'İstanbul Gelişim Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (95, 'İstanbul Kavram Meslek Yüksekokulu', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (96, 'İstanbul Kemerburgaz Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (97, 'İstanbul Kent Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (98, 'İstanbul Kültür Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (99, 'İstanbul Medeniyet Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (100, 'İstanbul Medipol Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (101, 'İstanbul Rumeli Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (102, 'İstanbul Sabahattin Zaim Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (103, 'İstanbul Şehir Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (104, 'İstanbul Şişli Meslek Yüksekokulu', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (105, 'İstanbul Teknik Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (106, 'İstanbul Ticaret Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (107, 'İstanbul Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (108, 'İstanbul Yeni Yüzyıl Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (109, 'İstinye Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (110, 'İzmir Bakırçay Üniversitesi', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (111, 'İzmir Demokrasi Üniversitesi', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (112, 'İzmir Ekonomi Üniversitesi', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (113, 'İzmir Katip Çelebi Üniversitesi', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (114, 'İzmir Yüksek Teknoloji Enstitüsü', 35);
INSERT INTO public.universities (id, university_name, city_id) VALUES (115, 'Kadir Has Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (116, 'Kafkas Üniversitesi', 36);
INSERT INTO public.universities (id, university_name, city_id) VALUES (117, 'Kahramanmaraş Sütçü İmam Üniversitesi', 46);
INSERT INTO public.universities (id, university_name, city_id) VALUES (118, 'Kapadokya Üniversitesi', 50);
INSERT INTO public.universities (id, university_name, city_id) VALUES (119, 'Karabük Üniversitesi', 78);
INSERT INTO public.universities (id, university_name, city_id) VALUES (120, 'Karadeniz Teknik Üniversitesi', 61);
INSERT INTO public.universities (id, university_name, city_id) VALUES (121, 'Karamanoğlu Mehmetbey Üniversitesi', 70);
INSERT INTO public.universities (id, university_name, city_id) VALUES (122, 'Kastamonu Üniversitesi', 37);
INSERT INTO public.universities (id, university_name, city_id) VALUES (123, 'Kırıkkale Üniversitesi', 71);
INSERT INTO public.universities (id, university_name, city_id) VALUES (124, 'Kırklareli Üniversitesi', 39);
INSERT INTO public.universities (id, university_name, city_id) VALUES (125, 'Kilis 7 Aralık Üniversitesi', 79);
INSERT INTO public.universities (id, university_name, city_id) VALUES (126, 'Kocaeli Üniversitesi', 41);
INSERT INTO public.universities (id, university_name, city_id) VALUES (127, 'Koç Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (128, 'Konya Gıda Ve Tarım Üniversitesi', 42);
INSERT INTO public.universities (id, university_name, city_id) VALUES (129, 'Kto Karatay Üniversitesi', 42);
INSERT INTO public.universities (id, university_name, city_id) VALUES (130, 'Maltepe Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (131, 'Manisa Celâl Bayar Üniversitesi', 45);
INSERT INTO public.universities (id, university_name, city_id) VALUES (132, 'Mardin Artuklu Üniversitesi', 47);
INSERT INTO public.universities (id, university_name, city_id) VALUES (133, 'Marmara Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (134, 'Mef Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (135, 'Mehmet Akif Ersoy Üniversitesi', 15);
INSERT INTO public.universities (id, university_name, city_id) VALUES (136, 'Melikşah Üniversitesi', 38);
INSERT INTO public.universities (id, university_name, city_id) VALUES (137, 'Mersin Üniversitesi', 33);
INSERT INTO public.universities (id, university_name, city_id) VALUES (138, 'Mimar Sinan Güzel Sanatlar Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (139, 'Muğla Sıtkı Koçman Üniversitesi', 48);
INSERT INTO public.universities (id, university_name, city_id) VALUES (140, 'Munzur Üniversitesi', 62);
INSERT INTO public.universities (id, university_name, city_id) VALUES (141, 'Mustafa Kemal Üniversitesi', 31);
INSERT INTO public.universities (id, university_name, city_id) VALUES (142, 'Muş Alparslan Üniversitesi', 49);
INSERT INTO public.universities (id, university_name, city_id) VALUES (143, 'Namık Kemal Üniversitesi', 59);
INSERT INTO public.universities (id, university_name, city_id) VALUES (144, 'Necmettin Erbakan Üniversitesi', 42);
INSERT INTO public.universities (id, university_name, city_id) VALUES (145, 'Nevşehir Hacı Bektaş Veli Üniversitesi', 50);
INSERT INTO public.universities (id, university_name, city_id) VALUES (146, 'Niğde Ömer Halisdemir Üniversitesi', 51);
INSERT INTO public.universities (id, university_name, city_id) VALUES (147, 'Niğde Üniversitesi', 51);
INSERT INTO public.universities (id, university_name, city_id) VALUES (148, 'Nişantaşı Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (149, 'Nuh Naci Yazgan Üniversitesi', 38);
INSERT INTO public.universities (id, university_name, city_id) VALUES (150, 'Okan Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (151, 'Ondokuz Mayıs Üniversitesi', 55);
INSERT INTO public.universities (id, university_name, city_id) VALUES (152, 'Ordu Üniversitesi', 52);
INSERT INTO public.universities (id, university_name, city_id) VALUES (153, 'Orta Doğu Teknik Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (154, 'Osmaniye Korkut Ata Üniversitesi', 80);
INSERT INTO public.universities (id, university_name, city_id) VALUES (155, 'Özyeğin Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (156, 'Pamukkale Üniversitesi', 20);
INSERT INTO public.universities (id, university_name, city_id) VALUES (157, 'Piri Reis Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (158, 'Recep Tayyip Erdoğan Üniversitesi', 53);
INSERT INTO public.universities (id, university_name, city_id) VALUES (159, 'Sabancı Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (160, 'Sağlık Bilimleri Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (161, 'Sakarya Üniversitesi', 54);
INSERT INTO public.universities (id, university_name, city_id) VALUES (162, 'Sanko Üniversitesi', 27);
INSERT INTO public.universities (id, university_name, city_id) VALUES (163, 'Selçuk Üniversitesi', 42);
INSERT INTO public.universities (id, university_name, city_id) VALUES (164, 'Siirt Üniversitesi', 56);
INSERT INTO public.universities (id, university_name, city_id) VALUES (165, 'Sinop Üniversitesi', 57);
INSERT INTO public.universities (id, university_name, city_id) VALUES (166, 'Süleyman Demirel Üniversitesi', 32);
INSERT INTO public.universities (id, university_name, city_id) VALUES (167, 'Şırnak Üniversitesi', 73);
INSERT INTO public.universities (id, university_name, city_id) VALUES (168, 'Ted Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (169, 'Tobb Ekonomi Ve Teknoloji Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (170, 'Toros Üniversitesi', 33);
INSERT INTO public.universities (id, university_name, city_id) VALUES (171, 'Trakya Üniversitesi', 22);
INSERT INTO public.universities (id, university_name, city_id) VALUES (172, 'Türk Hava Kurumu Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (173, 'Türk-Alman Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (174, 'Ufuk Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (175, 'Uludağ Üniversitesi', 16);
INSERT INTO public.universities (id, university_name, city_id) VALUES (176, 'Uşak Üniversitesi', 64);
INSERT INTO public.universities (id, university_name, city_id) VALUES (177, 'Üsküdar Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (178, 'Yalova Üniversitesi', 77);
INSERT INTO public.universities (id, university_name, city_id) VALUES (179, 'Yaşar Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (180, 'Yeditepe Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (181, 'Yıldız Teknik Üniversitesi', 34);
INSERT INTO public.universities (id, university_name, city_id) VALUES (182, 'Yüksek İhtisas Üniversitesi', 6);
INSERT INTO public.universities (id, university_name, city_id) VALUES (183, 'Yüzüncü Yıl Üniversitesi', 65);