-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_foreign_languages
(
    cv_id integer,
    language_level_id integer NOT NULL,
    foreign_languages_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    foreign_languages_name character varying(60) NOT NULL,
    PRIMARY KEY (foreign_languages_id)
);

CREATE TABLE public.cv_social_media
(
    cv_id integer NOT NULL,
    social_media_id integer NOT NULL,
    link character varying(200) NOT NULL,
    cv_social_media_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    PRIMARY KEY (cv_social_media_id)
);

CREATE TABLE public.cv_technologies
(
    cv_id integer NOT NULL,
    technology_id integer NOT NULL,
    cv_technologies_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    PRIMARY KEY (cv_technologies_id)
);

CREATE TABLE public.cvs
(
    cv_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 23504 CACHE 1 ),
    objective character varying(100),
    job_seeker_id integer NOT NULL,
    PRIMARY KEY (cv_id)
);

CREATE TABLE public.education_informations
(
    cv_id integer NOT NULL,
    university_id integer NOT NULL,
    university_department_id integer NOT NULL,
    start_date character varying(20) NOT NULL,
    graduation_date character varying(20),
    education_information_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    PRIMARY KEY (education_information_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    website character varying(100) NOT NULL,
    phone_number character varying(10) NOT NULL,
    verification_status boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_advertisement
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    job_position_id integer NOT NULL,
    city_id integer NOT NULL,
    job_description character varying(500) NOT NULL,
    min_salary integer,
    max_salary integer,
    number_of_open_positions integer NOT NULL,
    application_deadline character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    creation_date character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    identification_number character varying(11) NOT NULL,
    birth_year integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.language_levels
(
    language_level_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    language_level integer NOT NULL,
    PRIMARY KEY (language_level_id)
);

CREATE TABLE public.photos
(
    photo_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 3000000 CACHE 1 ),
    cv_id integer NOT NULL,
    photo_url character varying(100),
    PRIMARY KEY (photo_id)
);

CREATE TABLE public.social_media
(
    social_media_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    social_media_name character varying(100) NOT NULL,
    PRIMARY KEY (social_media_id)
);

CREATE TABLE public.system_personnel
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.technologies
(
    technology_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 23504 CACHE 1 ),
    technology_name character varying(100) NOT NULL,
    PRIMARY KEY (technology_id)
);

CREATE TABLE public.universities
(
    university_name character varying(100) NOT NULL,
    university_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    PRIMARY KEY (university_id)
);

CREATE TABLE public.university_departments
(
    university_department_name character varying(100) NOT NULL,
    university_department_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    PRIMARY KEY (university_department_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 9 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(250) NOT NULL,
    password character varying(250) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_experiences
(
    cv_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_id integer NOT NULL,
    workplace_name character varying(100) NOT NULL,
    start_date character varying(20) NOT NULL,
    end_date character varying(20),
    work_experience_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 30000 CACHE 1 ),
    PRIMARY KEY (work_experience_id)
);

ALTER TABLE public.cv_foreign_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.cv_foreign_languages
    ADD FOREIGN KEY (language_level_id)
    REFERENCES public.language_levels (language_level_id)
    NOT VALID;


ALTER TABLE public.cv_social_media
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.cv_social_media
    ADD FOREIGN KEY (social_media_id)
    REFERENCES public.social_media (social_media_id)
    NOT VALID;


ALTER TABLE public.cv_technologies
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.cv_technologies
    ADD FOREIGN KEY (technology_id)
    REFERENCES public.technologies (technology_id)
    NOT VALID;


ALTER TABLE public.cvs
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.education_informations
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.education_informations
    ADD FOREIGN KEY (university_department_id)
    REFERENCES public.university_departments (university_department_id)
    NOT VALID;


ALTER TABLE public.education_informations
    ADD FOREIGN KEY (university_id)
    REFERENCES public.universities (university_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.system_personnel
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.work_experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.work_experiences
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;

END;